version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9
    
    steps:
      - checkout
      - run:
          name: install dependencies and environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Test with pytest
          command: |
            . venv/bin/activate
            pytest
  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          # 1. Install Heroku CLI on the build machine
          # 2. Login to Heroku registry passing our Heroku API Key as a parameter
          #    to don’t need to authenticate with the Heroku login command. 
          # 3. Building and pushing our docker image to Heroku registry
          # 4. Releasing the new version of our app
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a oc-lettings-17 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings-17 web
# Orchestrate our job run sequence
workflows:
  main:
    jobs:
      - build-and-test
      - deploy-dev:
          requires:
            - build-and-test
          filters:
            branches:
              only: master # on the branch master only