version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.4
    
    steps:
      - checkout
      - run:
          name: Install dependencies and environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run linting
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Test with pytest
          command: |
            . venv/bin/activate
            pytest
  
  build-and-push-to-dockerhub:
    docker:
      - image: cimg/python:3.9.4
    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USER/python-oc-lettings:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
            docker tag $DOCKERHUB_USER/python-oc-lettings:$CIRCLE_SHA1 $DOCKERHUB_USER/python-oc-lettings:lastest
            docker push $DOCKERHUB_USER/python-oc-lettings:$CIRCLE_SHA1
            docker push $DOCKERHUB_USER/python-oc-lettings:lastest

  deploy-to-heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          # 1. Install Heroku CLI on the build machine
          # 2. Login to Heroku registry passing our Heroku API Key as a parameter
          #    to don’t need to authenticate with the Heroku login command. 
          # 3. Building and pushing our docker image to Heroku registry
          # 4. Releasing the new version of our app
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a oc-lettings-17 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a oc-lettings-17 web

# Orchestrate our job run sequence
workflows:
  main:
    jobs:
      - build-and-test
      - build-and-push-to-dockerhub:
          requires:
            - build-and-test
          filters:
            branches:
              only: master # on the branch master only
      - deploy-to-heroku:
          requires:
            - build-and-push-to-dockerhub
          filters:
            branches:
              only: master # on the branch master only